services:
  webapi1:
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

  webapi2:
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

  nginx:
    image: ${ENVOY_IMAGE:-envoyproxy/envoy}
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "error", "--concurrency", "1", "--disable-hot-restart"]
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"
