services:
  webapi1:
    cpuset: "0"
    security_opt:
      - seccomp=unconfined
    healthcheck:
      disable: true
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160MB"

  webapi2:
    cpuset: "1"
    security_opt:
      - seccomp=unconfined
    healthcheck:
      disable: true
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160MB"

  lb:
    image: jrblatt/so-no-forevis:v0.0.2
    container_name: rinha-lb
    pull_policy: always
    platform: linux/amd64
    cpuset: "2,3"
    user: root
    restart: always
    depends_on:
      - webapi1
      - webapi2
    environment:
      PORT: "9999"
      UPSTREAMS: /sockets/api1.sock,/sockets/api2.sock
      BUF_SIZE: "4096"
      WORKERS: "1"
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "30MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    security_opt:
      - seccomp=unconfined
