name: 'rinha-2026-dotnet'

services:
  webapi1: &webapi
    image: ghcr.io/jonathanperis/rinha4-back-end-dotnet:latest
    pull_policy: always
    container_name: webapi-1
    user: root
    restart: always
    read_only: true
    cpuset: "0,1"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "1"
      DOTNET_PROCESSOR_COUNT: "1"
      DOTNET_SYSTEM_NET_SOCKETS_INLINE_COMPLETIONS: "1"
      DOTNET_SYSTEM_NET_SOCKETS_THREAD_COUNT: "1"
      SOCKET_PATH: /sockets/api1.sock
      DATA_PATH: /data/references.bin
    tmpfs:
      - /tmp
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "150MB"

  webapi2:
    <<: *webapi
    container_name: webapi-2
    cpuset: "2,3"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "1"
      DOTNET_PROCESSOR_COUNT: "1"
      DOTNET_SYSTEM_NET_SOCKETS_INLINE_COMPLETIONS: "1"
      DOTNET_SYSTEM_NET_SOCKETS_THREAD_COUNT: "1"
      SOCKET_PATH: /sockets/api2.sock
      DATA_PATH: /data/references.bin
    tmpfs:
      - /tmp
    volumes:
      - sockets:/sockets

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    user: root
    cpuset: "0,2"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets
    depends_on:
      - webapi1
      - webapi2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=4m,mode=0777
