services:
  webapi1:
    environment:
      BIND_ADDR: fd:/sockets/api1.sock.ctrl
      FD_RAW: "0"
    deploy:
      resources:
        limits:
          cpus: "0.44"

  webapi2:
    environment:
      BIND_ADDR: fd:/sockets/api2.sock.ctrl
      FD_RAW: "0"
    deploy:
      resources:
        limits:
          cpus: "0.44"

  lb:
    image: ${LB_IMAGE:-ghcr.io/jonathanperis/rinha4-lb-yolo-mode:asm-ci-dcc6b89ca9d21c7a8dbb1588a6bfbbc0bd20bb91}
    environment:
      LB_MODE: "fdpass"
      LB_FDPASS_SOCKET_TYPE: "stream"
      UPSTREAMS: "/sockets/api1.sock.ctrl,/sockets/api2.sock.ctrl"
    deploy:
      resources:
        limits:
          cpus: "0.12"
