services:
  lb:
    image: ${WEBAPI_IMAGE:-ghcr.io/jonathanperis/rinha4-back-end-dotnet:latest}
    container_name: rinha-lb
    user: root
    entrypoint: ["/rinha-lb"]
    volumes:
      - sockets:/sockets
    depends_on:
      webapi1:
        condition: service_healthy
      webapi2:
        condition: service_healthy
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.24"
          memory: "32MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
