services:
  nginx:
    image: haproxy:latest
    container_name: haproxy-lb
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "20MB"
