worker_processes auto;

events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

stream {
    upstream api {
        server unix:/sockets/api1.sock;
        server unix:/sockets/api2.sock;
    }

    server {
        listen 9999;
        proxy_pass api;
        proxy_timeout 3s;
        proxy_connect_timeout 1s;
    }
}
