services:
  api-1:
    image: luanmonteiro1/qrust-concept-api:latest
    container_name: qrust-concept-api-1
    environment:
      - API_SOCKET=/var/run/rinha/api1.sock
      - SEARCH_STRATEGY=S3B
    volumes:
      - socket-dir:/var/run/rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 167MB
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost/ready', { unix: '/var/run/rinha/api1.sock' }).then(r => r.status === 200 || process.exit(1))"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 20s

  api-2:
    image: luanmonteiro1/qrust-concept-api:latest
    container_name: qrust-concept-api-2
    environment:
      - API_SOCKET=/var/run/rinha/api2.sock
      - SEARCH_STRATEGY=S3B
    volumes:
      - socket-dir:/var/run/rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 167MB
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost/ready', { unix: '/var/run/rinha/api2.sock' }).then(r => r.status === 200 || process.exit(1))"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 20s

  lb:
    image: haproxy:3.0-alpine
    container_name: haproxy-lb
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - socket-dir:/var/run/rinha
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-db"]
    ports:
      - "9999:9999"
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 15MB

volumes:
  socket-dir: {}
