services:
  api1: &api
    image: mxlange/c-api-rinha2026@sha256:f3dbcafb9f5835925445cb636040c31288a9ba73e9c2b6006cc48ba9a331e9e5
    platform: linux/amd64
    environment:
      - FD_SOCKET=/run/sock/api1.sock
      - INDEX_PATH=/app/data/knn.idx
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    <<: *api
    environment:
      - FD_SOCKET=/run/sock/api2.sock
      - INDEX_PATH=/app/data/knn.idx

  lb:
    image: mxlange/c-api-rinha2026@sha256:f3dbcafb9f5835925445cb636040c31288a9ba73e9c2b6006cc48ba9a331e9e5
    platform: linux/amd64
    command: ["/app/lb"]
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    environment:
      - PORT=9999
      - FD_UPSTREAMS=/run/sock/api1.sock,/run/sock/api2.sock
      - WORKERS=2
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m
