global using System.Buffers;
global using System.Globalization;
global using System.Net;
global using System.Net.Sockets;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using System.Text;
global using System.Text.Json;
