name: rinha-2026-hanake0

services:
  lb:
    image: ghcr.io/hanake0/rinha-backend-2026-csharp-nativeaot-lb:submission-v17
    pull_policy: always
    platform: linux/amd64
    security_opt:
      - seccomp=unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9999:9999"
    environment:
      ASPNETCORE_URLS: http://+:9999
      BACKEND_ENDPOINTS: unix:/sockets/api1.sock;unix:/sockets/api2.sock
      LOAD_BALANCER_MODE: IoUring
      LB_ENGINE_COUNT: "1"
    depends_on:
      - api1
      - api2
    volumes:
      - uds-sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"

  api1: &api
    image: ghcr.io/hanake0/rinha-backend-2026-csharp-nativeaot-api:submission-v17-fat
    pull_policy: always
    platform: linux/amd64
    security_opt:
      - seccomp=unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    environment:
      API_ENGINE_COUNT: "1"
      API_UNIX_SOCKET_PATH: /sockets/api1.sock
      Runtime__Detection__ApprovalThreshold: "0.6"
      Runtime__Detection__TopK: "5"
      Runtime__Dataset__IndexDirectory: /app/data/index
      Runtime__Dataset__MccRiskPath: /app/data/mcc_risk.json
      Runtime__Dataset__NormalizationPath: /app/data/normalization.json
      Runtime__Http__ParserMode: Manual
      Runtime__Http__ServerMode: IoUring
      Runtime__Search__ExecutionMode: Local
      Runtime__Search__IndexStorageMode: MemoryMapped
      Runtime__Search__BeamLevel1: "8"
      Runtime__Search__BeamLevel2: "128"
      Runtime__Search__BoundaryBeamLevel2: "0"
      Runtime__Search__RerankCount: "48"
      Runtime__Search__BoundaryRerankCount: "48"
      Runtime__Search__UseLeafRadiusPruning: "true"
      Runtime__Search__UseLastTransactionPartitionPruning: "false"
    volumes:
      - uds-sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

  api2:
    <<: *api
    environment:
      API_ENGINE_COUNT: "1"
      API_UNIX_SOCKET_PATH: /sockets/api2.sock
      Runtime__Detection__ApprovalThreshold: "0.6"
      Runtime__Detection__TopK: "5"
      Runtime__Dataset__IndexDirectory: /app/data/index
      Runtime__Dataset__MccRiskPath: /app/data/mcc_risk.json
      Runtime__Dataset__NormalizationPath: /app/data/normalization.json
      Runtime__Http__ParserMode: Manual
      Runtime__Http__ServerMode: IoUring
      Runtime__Search__ExecutionMode: Local
      Runtime__Search__IndexStorageMode: MemoryMapped
      Runtime__Search__BeamLevel1: "8"
      Runtime__Search__BeamLevel2: "128"
      Runtime__Search__BoundaryBeamLevel2: "0"
      Runtime__Search__RerankCount: "48"
      Runtime__Search__BoundaryRerankCount: "48"
      Runtime__Search__UseLeafRadiusPruning: "true"
      Runtime__Search__UseLastTransactionPartitionPruning: "false"

volumes:
  uds-sockets:
